//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStoreMVC.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_BookList
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "*")]
        public string BookName { get; set; }

        [Required(ErrorMessage = "*")]
        public string Category { get; set; }

        [Required(ErrorMessage = "*")]
        public string Price { get; set; }
    }
}
